version: '3.8'
services:
  postgres:
    image: postgres:15-alpine
    container_name: estacionamento_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: estacionamento_laravel
      POSTGRES_USER: estacionamento
      POSTGRES_PASSWORD: oi
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
